export class SelectionManager {
  constructor(canvasManager, state) { this.canvasManager = canvasManager; this.state = state; this.selection = null; this.dragStart = null; this.image = null; }
  start(point) { this.dragStart = point; }
  preview(point) { if (!this.dragStart) return; const { context } = this.canvasManager; context.save(); context.setLineDash([6, 4]); context.strokeStyle = '#2563eb'; context.lineWidth = 1; context.strokeRect(this.dragStart.x, this.dragStart.y, point.x - this.dragStart.x, point.y - this.dragStart.y); context.restore(); }
  finish(point) { if (!this.dragStart) return; const x = Math.min(this.dragStart.x, point.x); const y = Math.min(this.dragStart.y, point.y); const width = Math.abs(point.x - this.dragStart.x); const height = Math.abs(point.y - this.dragStart.y); this.selection = width > 2 && height > 2 ? { x: Math.floor(x), y: Math.floor(y), width: Math.floor(width), height: Math.floor(height) } : null; this.dragStart = null; this.capture(); }
  capture() { if (!this.selection) return; const s = this.selection; this.image = this.canvasManager.context.getImageData(s.x, s.y, s.width, s.height); }
  clear() { this.selection = null; this.image = null; }
  delete() { if (!this.selection) return false; const { context } = this.canvasManager; context.fillStyle = this.state.backgroundColor; context.fillRect(this.selection.x, this.selection.y, this.selection.width, this.selection.height); this.clear(); return true; }
  transform(kind) { if (!this.selection || !this.image) return false; const s = this.selection; const temp = document.createElement('canvas'); temp.width = s.width; temp.height = s.height; temp.getContext('2d').putImageData(this.image, 0, 0); const { context } = this.canvasManager; context.fillStyle = this.state.backgroundColor; context.fillRect(s.x, s.y, s.width, s.height); context.save(); context.translate(s.x + s.width / 2, s.y + s.height / 2); if (kind === 'rotate') context.rotate(Math.PI / 12); if (kind === 'scale') context.scale(1.1, 1.1); if (kind === 'reflect-x') context.scale(1, -1); if (kind === 'reflect-y') context.scale(-1, 1); context.drawImage(temp, -s.width / 2, -s.height / 2); context.restore(); this.capture(); return true; }
}
