import { AppState } from './core/AppState.js';
import { CanvasManager } from './core/CanvasManager.js';
import { PencilTool } from './tools/PencilTool.js';
import { BrushTool } from './tools/BrushTool.js';
import { EraserTool } from './tools/EraserTool.js';
import { ShapeTool } from './tools/ShapeTool.js';
import { FillTool } from './tools/FillTool.js';
import { SelectionTool } from './tools/SelectionTool.js';
import { EmojiTool } from './tools/EmojiTool.js';
import { PictureTool } from './tools/PictureTool.js';
import { ThreeDTool } from './tools/ThreeDTool.js';
import { TextTool } from './tools/TextTool.js';
import { HistoryManager } from './managers/HistoryManager.js';
import { SelectionManager } from './managers/SelectionManager.js';
import { downloadCanvas, loadImage } from './utils/fileUtils.js';

const state = new AppState(); const canvas = document.querySelector('#drawing-canvas'); const canvasManager = new CanvasManager(canvas, state); const history = new HistoryManager(canvasManager); const selection = new SelectionManager(canvasManager, state);
const $ = (id) => document.querySelector(id);
const elements = { splash: $('#splash-screen'), openWorkspace: $('#open-workspace'), themeToggle: $('#theme-toggle'), themeIcon: $('#theme-icon'), themeLabel: $('#theme-label'), width: $('#canvas-width'), height: $('#canvas-height'), widthOutput: $('#canvas-width-output'), heightOutput: $('#canvas-height-output'), background: $('#background-color'), foreground: $('#foreground-color'), brushSize: $('#brush-size'), brushSizeOutput: $('#brush-size-output'), lineAlgorithm: $('#line-algorithm'), fillAlgorithm: $('#fill-algorithm'), visualize: $('#visualize'), emojiPanel: $('#emoji-panel'), emojiButtons: document.querySelectorAll('[data-emoji]'), selectedEmoji: $('#selected-emoji'), closeEmoji: $('#close-emoji-panel'), viewAngle: $('#view-angle'), viewAngleOutput: $('#view-angle-output'), textContent: $('#text-content'), fontFamily: $('#font-family'), fontWeight: $('#font-weight'), textSize: $('#text-size'), textSizeOutput: $('#text-size-output'), toolButtons: document.querySelectorAll('[data-tool]'), canvasLabel: $('#canvas-label'), coordinateDisplay: $('#coordinate-display'), status: $('#status-message'), algorithm: $('#algorithm-display'), clear: $('#clear-canvas'), newCanvas: $('#new-canvas'), undo: $('#undo'), redo: $('#redo'), open: $('#open-image'), file: $('#open-file'), pictureFile: $('#picture-file'), png: $('#export-png'), jpg: $('#export-jpg'), zoomIn: $('#zoom-in'), zoomOut: $('#zoom-out'), zoomLabel: $('#zoom-label'), transforms: document.querySelectorAll('[data-transform]'), deleteSelection: $('#delete-selection') };
const info = (message) => { elements.algorithm.textContent = message; };
const tools = { pencil: new PencilTool(canvasManager, state), brush: new BrushTool(canvasManager, state), eraser: new EraserTool(canvasManager, state), line: new ShapeTool(canvasManager, state, 'line', info), rectangle: new ShapeTool(canvasManager, state, 'rectangle', info), circle: new ShapeTool(canvasManager, state, 'circle', info), ellipse: new ShapeTool(canvasManager, state, 'ellipse', info), triangle: new ShapeTool(canvasManager, state, 'triangle', info), polygon: new ShapeTool(canvasManager, state, 'polygon', info), fill: new FillTool(canvasManager, state, info), select: new SelectionTool(canvasManager, state, selection), picture: new PictureTool(canvasManager, state), emoji: new EmojiTool(canvasManager, state), 'three-d': new ThreeDTool(canvasManager, state), text: new TextTool(canvasManager, state) };
Object.entries(tools).forEach(([name, tool]) => { tool.name ??= name[0].toUpperCase() + name.slice(1); }); let isDrawing = false;
function updateSizeLabels() { elements.widthOutput.value = `${state.canvasWidth} px`; elements.heightOutput.value = `${state.canvasHeight} px`; elements.canvasLabel.textContent = `${state.canvasWidth} × ${state.canvasHeight}`; }
function updateZoom() { canvas.style.width = `${state.canvasWidth * state.zoom}px`; canvas.style.height = `${state.canvasHeight * state.zoom}px`; elements.zoomLabel.textContent = `${Math.round(state.zoom * 100)}%`; }
function selectTool(name) { state.currentTool = name; elements.toolButtons.forEach((button) => { const selected = button.dataset.tool === name; button.classList.toggle('is-active', selected); button.setAttribute('aria-pressed', String(selected)); }); elements.status.textContent = `${tools[name].name} selected`; }
function toggleEmojiPanel(show) { const isOpen = show ?? elements.emojiPanel.hidden; elements.emojiPanel.hidden = !isOpen; const emojiToolButton = document.querySelector('[data-tool="emoji"]'); emojiToolButton.setAttribute('aria-expanded', String(isOpen)); }
function applyTheme(theme) { const dark = theme === 'dark'; document.body.classList.toggle('theme-dark', dark); elements.themeToggle.setAttribute('aria-pressed', String(dark)); elements.themeToggle.title = `Switch to ${dark ? 'light' : 'dark'} theme`; elements.themeIcon.textContent = dark ? '☀' : '☾'; elements.themeLabel.textContent = dark ? 'Light' : 'Dark'; try { localStorage.setItem('graphidraw-theme', theme); } catch { /* Storage may be unavailable in private contexts. */ } }
function saveAction(message = 'Action complete') { history.capture(); elements.status.textContent = message; }
function resizeCanvas() { canvasManager.resize(Number(elements.width.value), Number(elements.height.value)); updateSizeLabels(); updateZoom(); history.reset(); elements.status.textContent = 'Canvas resized'; }
function setZoom(delta) { state.zoom = Math.min(4, Math.max(.25, state.zoom + delta)); updateZoom(); }
elements.width.addEventListener('input', resizeCanvas); elements.height.addEventListener('input', resizeCanvas);
elements.openWorkspace.addEventListener('click', () => { elements.splash.classList.add('is-hidden'); setTimeout(() => elements.splash.remove(), 600); });
elements.themeToggle.addEventListener('click', () => applyTheme(document.body.classList.contains('theme-dark') ? 'light' : 'dark'));
elements.background.addEventListener('input', (event) => { state.backgroundColor = event.target.value; elements.status.textContent = 'Background color selected'; }); elements.foreground.addEventListener('input', (event) => { state.foregroundColor = event.target.value; elements.status.textContent = 'Drawing color selected'; }); elements.brushSize.addEventListener('input', (event) => { state.brushSize = Number(event.target.value); elements.brushSizeOutput.value = `${state.brushSize} px`; });
elements.lineAlgorithm.addEventListener('change', (event) => { state.lineAlgorithm = event.target.value; info(`${event.target.value.toUpperCase()} selected`); }); elements.fillAlgorithm.addEventListener('change', (event) => { state.fillAlgorithm = event.target.value; info(`${event.target.value === 'flood' ? 'Flood fill' : 'Boundary fill'} selected`); }); elements.visualize.addEventListener('change', (event) => { state.visualize = event.target.checked; info(state.visualize ? 'Algorithm details will appear while drawing' : 'Algorithm details hidden'); }); elements.viewAngle.addEventListener('input', (event) => { state.viewAngle = Number(event.target.value); elements.viewAngleOutput.value = `${state.viewAngle}°`; }); elements.textContent.addEventListener('input', (event) => { state.textContent = event.target.value; }); elements.fontFamily.addEventListener('change', (event) => { state.fontFamily = event.target.value; }); elements.fontWeight.addEventListener('change', (event) => { state.fontWeight = event.target.value; }); elements.textSize.addEventListener('input', (event) => { state.textSize = Number(event.target.value); elements.textSizeOutput.value = `${state.textSize} px`; }); elements.toolButtons.forEach((button) => button.addEventListener('click', () => { if (button.dataset.tool === 'picture') elements.pictureFile.click(); else if (button.dataset.tool === 'emoji') { selectTool('emoji'); toggleEmojiPanel(); } else selectTool(button.dataset.tool); })); elements.closeEmoji.addEventListener('click', () => toggleEmojiPanel(false)); elements.emojiButtons.forEach((button) => button.addEventListener('click', () => { state.emoji = button.dataset.emoji; elements.selectedEmoji.textContent = state.emoji; elements.emojiButtons.forEach((item) => item.classList.toggle('is-selected', item === button)); selectTool('emoji'); toggleEmojiPanel(false); elements.status.textContent = `${state.emoji} selected — click the canvas to stamp it`; }));
elements.clear.addEventListener('click', () => { canvasManager.clear(); selection.clear(); saveAction('Canvas cleared'); }); elements.newCanvas.addEventListener('click', () => { canvasManager.clear(); selection.clear(); history.reset(); elements.status.textContent = 'New blank canvas'; }); elements.undo.addEventListener('click', () => { elements.status.textContent = history.undo() ? 'Undone' : 'Nothing to undo'; }); elements.redo.addEventListener('click', () => { elements.status.textContent = history.redo() ? 'Redone' : 'Nothing to redo'; });
elements.png.addEventListener('click', () => downloadCanvas(canvas, 'png')); elements.jpg.addEventListener('click', () => downloadCanvas(canvas, 'jpeg')); elements.open.addEventListener('click', () => elements.file.click()); elements.file.addEventListener('change', async () => { try { await loadImage(elements.file.files[0], canvasManager); state.canvasWidth = canvas.width; state.canvasHeight = canvas.height; elements.width.value = Math.min(1400, canvas.width); elements.height.value = Math.min(1000, canvas.height); updateSizeLabels(); updateZoom(); history.reset(); elements.status.textContent = 'Image opened'; } catch (error) { elements.status.textContent = error.message; } finally { elements.file.value = ''; } });
elements.pictureFile.addEventListener('change', () => { const file = elements.pictureFile.files[0]; if (!file) return; const image = new Image(); image.onload = () => { tools.picture.setImage(image); selectTool('picture'); elements.status.textContent = 'Click the canvas to place the picture'; }; image.onerror = () => { elements.status.textContent = 'The picture could not be opened'; }; image.src = URL.createObjectURL(file); elements.pictureFile.value = ''; });
elements.zoomIn.addEventListener('click', () => setZoom(.25)); elements.zoomOut.addEventListener('click', () => setZoom(-.25)); elements.transforms.forEach((button) => button.addEventListener('click', () => { if (selection.transform(button.dataset.transform)) saveAction('Selection transformed'); else elements.status.textContent = 'Select a region first'; })); elements.deleteSelection.addEventListener('click', () => { if (selection.delete()) saveAction('Selection deleted'); else elements.status.textContent = 'Select a region first'; });
canvas.addEventListener('pointermove', (event) => { const point = canvasManager.getCanvasPoint(event); elements.coordinateDisplay.textContent = `X: ${point.x}   Y: ${point.y}`; if (isDrawing) tools[state.currentTool].pointerMove(point); }); canvas.addEventListener('pointerdown', (event) => { if (event.button !== 0) return; isDrawing = true; canvas.setPointerCapture(event.pointerId); const result = tools[state.currentTool].pointerDown(canvasManager.getCanvasPoint(event)); if (result === false) { isDrawing = false; canvas.releasePointerCapture(event.pointerId); elements.status.textContent = state.currentTool === 'text' ? 'Type text in the Text tool panel first' : 'Choose a picture first'; return; } elements.status.textContent = `Using ${tools[state.currentTool].name.toLowerCase()}`; });
function finishStroke(event) { if (!isDrawing) return; isDrawing = false; tools[state.currentTool].pointerUp(canvasManager.getCanvasPoint(event)); if (canvas.hasPointerCapture(event.pointerId)) canvas.releasePointerCapture(event.pointerId); saveAction('Stroke complete'); }
canvas.addEventListener('pointerup', finishStroke); canvas.addEventListener('pointercancel', () => { isDrawing = false; tools[state.currentTool].pointerUp(); }); canvas.addEventListener('pointerleave', () => { if (!isDrawing) elements.coordinateDisplay.textContent = 'X: —   Y: —'; });
window.addEventListener('keydown', (event) => { const modifier = event.ctrlKey || event.metaKey; if (modifier && event.key.toLowerCase() === 'z') { event.preventDefault(); elements.status.textContent = history.undo() ? 'Undone' : 'Nothing to undo'; } else if (modifier && event.key.toLowerCase() === 'y') { event.preventDefault(); elements.status.textContent = history.redo() ? 'Redone' : 'Nothing to redo'; } else if (modifier && event.key.toLowerCase() === 's') { event.preventDefault(); downloadCanvas(canvas, 'png'); } else if (modifier && event.key.toLowerCase() === 'o') { event.preventDefault(); elements.file.click(); } else if (modifier && event.key.toLowerCase() === 'n') { event.preventDefault(); canvasManager.clear(); history.reset(); } else if (!modifier && !event.altKey && !event.target.matches('input, select, textarea')) { const short = { p: 'pencil', b: 'brush', e: 'eraser', l: 'line', r: 'rectangle', c: 'circle', f: 'fill', v: 'select', t: 'text' }[event.key.toLowerCase()]; if (short) selectTool(short); if (event.key === 'Delete' && selection.delete()) saveAction('Selection deleted'); } });
try { applyTheme(localStorage.getItem('graphidraw-theme') || 'light'); } catch { applyTheme('light'); } updateSizeLabels(); elements.brushSizeOutput.value = `${state.brushSize} px`; elements.viewAngleOutput.value = `${state.viewAngle}°`; elements.textSizeOutput.value = `${state.textSize} px`; updateZoom();
