import { AppState } from './core/AppState.js';
import { CanvasManager } from './core/CanvasManager.js';
import { PencilTool } from './tools/PencilTool.js';
import { BrushTool } from './tools/BrushTool.js';
import { EraserTool } from './tools/EraserTool.js';
import { ShapeTool } from './tools/ShapeTool.js';
import { FillTool } from './tools/FillTool.js';
import { SelectionTool } from './tools/SelectionTool.js';
import { HistoryManager } from './managers/HistoryManager.js';
import { SelectionManager } from './managers/SelectionManager.js';
import { downloadCanvas, loadImage } from './utils/fileUtils.js';

const state = new AppState(); const canvas = document.querySelector('#drawing-canvas'); const canvasManager = new CanvasManager(canvas, state); const history = new HistoryManager(canvasManager); const selection = new SelectionManager(canvasManager, state);
const $ = (id) => document.querySelector(id);
const elements = { width: $('#canvas-width'), height: $('#canvas-height'), widthOutput: $('#canvas-width-output'), heightOutput: $('#canvas-height-output'), background: $('#background-color'), foreground: $('#foreground-color'), brushSize: $('#brush-size'), brushSizeOutput: $('#brush-size-output'), lineAlgorithm: $('#line-algorithm'), fillAlgorithm: $('#fill-algorithm'), visualize: $('#visualize'), toolButtons: document.querySelectorAll('[data-tool]'), canvasLabel: $('#canvas-label'), coordinateDisplay: $('#coordinate-display'), status: $('#status-message'), algorithm: $('#algorithm-display'), clear: $('#clear-canvas'), newCanvas: $('#new-canvas'), undo: $('#undo'), redo: $('#redo'), open: $('#open-image'), file: $('#open-file'), png: $('#export-png'), jpg: $('#export-jpg'), zoomIn: $('#zoom-in'), zoomOut: $('#zoom-out'), zoomLabel: $('#zoom-label'), transforms: document.querySelectorAll('[data-transform]'), deleteSelection: $('#delete-selection') };
const info = (message) => { elements.algorithm.textContent = message; };
const tools = { pencil: new PencilTool(canvasManager, state), brush: new BrushTool(canvasManager, state), eraser: new EraserTool(canvasManager, state), line: new ShapeTool(canvasManager, state, 'line', info), rectangle: new ShapeTool(canvasManager, state, 'rectangle', info), circle: new ShapeTool(canvasManager, state, 'circle', info), ellipse: new ShapeTool(canvasManager, state, 'ellipse', info), triangle: new ShapeTool(canvasManager, state, 'triangle', info), polygon: new ShapeTool(canvasManager, state, 'polygon', info), fill: new FillTool(canvasManager, state, info), select: new SelectionTool(canvasManager, state, selection) };
Object.entries(tools).forEach(([name, tool]) => { tool.name ??= name[0].toUpperCase() + name.slice(1); }); let isDrawing = false;
function updateSizeLabels() { elements.widthOutput.value = `${state.canvasWidth} px`; elements.heightOutput.value = `${state.canvasHeight} px`; elements.canvasLabel.textContent = `${state.canvasWidth} × ${state.canvasHeight}`; }
function updateZoom() { canvas.style.width = `${state.canvasWidth * state.zoom}px`; canvas.style.height = `${state.canvasHeight * state.zoom}px`; elements.zoomLabel.textContent = `${Math.round(state.zoom * 100)}%`; }
function selectTool(name) { state.currentTool = name; elements.toolButtons.forEach((button) => { const selected = button.dataset.tool === name; button.classList.toggle('is-active', selected); button.setAttribute('aria-pressed', String(selected)); }); elements.status.textContent = `${tools[name].name} selected`; }
function saveAction(message = 'Action complete') { history.capture(); elements.status.textContent = message; }
function resizeCanvas() { canvasManager.resize(Number(elements.width.value), Number(elements.height.value)); updateSizeLabels(); updateZoom(); history.reset(); elements.status.textContent = 'Canvas resized'; }
function setZoom(delta) { state.zoom = Math.min(4, Math.max(.25, state.zoom + delta)); updateZoom(); }
elements.width.addEventListener('input', resizeCanvas); elements.height.addEventListener('input', resizeCanvas);
elements.background.addEventListener('input', (event) => { state.backgroundColor = event.target.value; elements.status.textContent = 'Background color selected'; }); elements.foreground.addEventListener('input', (event) => { state.foregroundColor = event.target.value; elements.status.textContent = 'Drawing color selected'; }); elements.brushSize.addEventListener('input', (event) => { state.brushSize = Number(event.target.value); elements.brushSizeOutput.value = `${state.brushSize} px`; });
elements.lineAlgorithm.addEventListener('change', (event) => { state.lineAlgorithm = event.target.value; info(`${event.target.value.toUpperCase()} selected`); }); elements.fillAlgorithm.addEventListener('change', (event) => { state.fillAlgorithm = event.target.value; info(`${event.target.value === 'flood' ? 'Flood fill' : 'Boundary fill'} selected`); }); elements.visualize.addEventListener('change', (event) => { state.visualize = event.target.checked; info(state.visualize ? 'Algorithm details will appear while drawing' : 'Algorithm details hidden'); }); elements.toolButtons.forEach((button) => button.addEventListener('click', () => selectTool(button.dataset.tool)));
elements.clear.addEventListener('click', () => { canvasManager.clear(); selection.clear(); saveAction('Canvas cleared'); }); elements.newCanvas.addEventListener('click', () => { canvasManager.clear(); selection.clear(); history.reset(); elements.status.textContent = 'New blank canvas'; }); elements.undo.addEventListener('click', () => { elements.status.textContent = history.undo() ? 'Undone' : 'Nothing to undo'; }); elements.redo.addEventListener('click', () => { elements.status.textContent = history.redo() ? 'Redone' : 'Nothing to redo'; });
elements.png.addEventListener('click', () => downloadCanvas(canvas, 'png')); elements.jpg.addEventListener('click', () => downloadCanvas(canvas, 'jpeg')); elements.open.addEventListener('click', () => elements.file.click()); elements.file.addEventListener('change', async () => { try { await loadImage(elements.file.files[0], canvasManager); state.canvasWidth = canvas.width; state.canvasHeight = canvas.height; elements.width.value = Math.min(1400, canvas.width); elements.height.value = Math.min(1000, canvas.height); updateSizeLabels(); updateZoom(); history.reset(); elements.status.textContent = 'Image opened'; } catch (error) { elements.status.textContent = error.message; } finally { elements.file.value = ''; } });
elements.zoomIn.addEventListener('click', () => setZoom(.25)); elements.zoomOut.addEventListener('click', () => setZoom(-.25)); elements.transforms.forEach((button) => button.addEventListener('click', () => { if (selection.transform(button.dataset.transform)) saveAction('Selection transformed'); else elements.status.textContent = 'Select a region first'; })); elements.deleteSelection.addEventListener('click', () => { if (selection.delete()) saveAction('Selection deleted'); else elements.status.textContent = 'Select a region first'; });
canvas.addEventListener('pointermove', (event) => { const point = canvasManager.getCanvasPoint(event); elements.coordinateDisplay.textContent = `X: ${point.x}   Y: ${point.y}`; if (isDrawing) tools[state.currentTool].pointerMove(point); }); canvas.addEventListener('pointerdown', (event) => { if (event.button !== 0) return; isDrawing = true; canvas.setPointerCapture(event.pointerId); tools[state.currentTool].pointerDown(canvasManager.getCanvasPoint(event)); elements.status.textContent = `Using ${tools[state.currentTool].name.toLowerCase()}`; });
function finishStroke(event) { if (!isDrawing) return; isDrawing = false; tools[state.currentTool].pointerUp(canvasManager.getCanvasPoint(event)); if (canvas.hasPointerCapture(event.pointerId)) canvas.releasePointerCapture(event.pointerId); saveAction('Stroke complete'); }
canvas.addEventListener('pointerup', finishStroke); canvas.addEventListener('pointercancel', () => { isDrawing = false; tools[state.currentTool].pointerUp(); }); canvas.addEventListener('pointerleave', () => { if (!isDrawing) elements.coordinateDisplay.textContent = 'X: —   Y: —'; });
window.addEventListener('keydown', (event) => { const modifier = event.ctrlKey || event.metaKey; if (modifier && event.key.toLowerCase() === 'z') { event.preventDefault(); elements.status.textContent = history.undo() ? 'Undone' : 'Nothing to undo'; } else if (modifier && event.key.toLowerCase() === 'y') { event.preventDefault(); elements.status.textContent = history.redo() ? 'Redone' : 'Nothing to redo'; } else if (modifier && event.key.toLowerCase() === 's') { event.preventDefault(); downloadCanvas(canvas, 'png'); } else if (modifier && event.key.toLowerCase() === 'o') { event.preventDefault(); elements.file.click(); } else if (modifier && event.key.toLowerCase() === 'n') { event.preventDefault(); canvasManager.clear(); history.reset(); } else if (!modifier && !event.altKey && !event.target.matches('input, select')) { const short = { p: 'pencil', b: 'brush', e: 'eraser', l: 'line', r: 'rectangle', c: 'circle', f: 'fill', v: 'select' }[event.key.toLowerCase()]; if (short) selectTool(short); if (event.key === 'Delete' && selection.delete()) saveAction('Selection deleted'); } });
updateSizeLabels(); elements.brushSizeOutput.value = `${state.brushSize} px`; updateZoom();
